#!/usr/bin/env bash
set -eu
[ -n "$PLENV_DEBUG" ] && set -x

indent_output() {
  while read data; do
    echo -e " \033[1;32m|\033[0m  $data"
  done
}

plenv_update() {
  echo -e "\033[1;32mupdating $1\033[0m"
  git checkout master 2>&1 | indent_output
  for remote in $(git remote)
  do
    git fetch ${remote} 2>&1 | indent_output
    git pull ${remote} master 2>&1 | indent_output
  done
  echo
}

main() {
  cd ${PLENV_ROOT:-$(plenv root)}
  plenv_update plenv

  plugins=plugins/*
  for plugin in ${plugins[@]}; do
    if [ -d $plugin/.git ]; then
      cd $plugin
      plenv_update $(basename $plugin)
      cd - >/dev/null
    fi
  done
}

main
